import './globals.css'
import { Inter, Open_Sans, Montserrat, Old_Standard_TT } from 'next/font/google'
const inter = Inter({
   subsets: ['latin'],
   variable: '--font-inter',
   weight: '500',
   })
const openSans = Open_Sans({
   subsets: ['latin'],
    variable: '--font-open-sans',
    weight: '600',
  })
const montserrat = Montserrat({
   subsets: ['latin'],
    variable: '--font-montserrat',
    weight: '500',
  })
const oldStandard = Old_Standard_TT({
   subsets: ['latin'],weight: '700',
    variable: '--font-old-standard-tt', 
  })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${openSans.variable} ${montserrat.variable} ${oldStandard.variable}`}>
      <nav className=' bg-navbar w-screen h-auto py-2 flex flex-col '>
        <button className=' absolute top-6 left-8 h-8 w-8 cursor-pointer'>
          <div className=" h-0.5 w-6 rounded-none bg-white before:absolute before:h-0.5 before:w-6 before:-translate-x-3 before:-translate-y-2 before:rounded before:bg-white before:content-[''] after:absolute after:h-0.5 after:w-6 after:-translate-x-3 after:translate-y-2 after:rounded after:bg-white after:content-['']">

          </div>
        </button>
        <h1 className=' font-oldStandardTT text-3xl text-orange-300 max-md:text-center'>M</h1>
        <p className=' font-openSans text-white max-md:text-center text-xs'>Manifesto</p>
      </nav>
        {children}
        </body>
    </html>
  )
}
