import {
  Inter,
  Montserrat,
  Old_Standard_TT,
  Open_Sans,
} from 'next/font/google';
import Navbar from './components/navbar/Navbar';
import './globals.css';
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  weight: '500',
});
const openSans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-open-sans',
  weight: '600',
});
const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  weight: '500',
});
const oldStandard = Old_Standard_TT({
  subsets: ['latin'],
  weight: '700',
  variable: '--font-old-standard-tt',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${openSans.variable} ${montserrat.variable} ${oldStandard.variable}`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
